project_id = "emolyyvmvvfjyxbguhyn"

[functions.send-app-link]
verify_jwt = false

[functions.ai-financial-advisor]
verify_jwt = true

[functions.sumsub-issue-token]
verify_jwt = true

[functions.payments-circle-webhook]
verify_jwt = false

[functions.health]
verify_jwt = false