
name: Android APK & AAB with Daily Auto-versioning

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-apks-and-aab:
    runs-on: ubuntu-latest
    env:
      ANDROID_KEYSTORE_PATH: keystore.jks
      AIKEYS_BASE_URL: https://aikeys-hub.com
      PACKAGE_NAME: com.aikeys.wallet

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch tags for versioning
        run: git fetch --tags || echo "No tags found"

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make Gradle wrapper executable
        working-directory: android
        run: chmod +x ./gradlew

      # Debug APK
      - name: Build Debug APK
        working-directory: android
        run: ./gradlew assembleDebug --no-daemon
        
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: AIKEYS-debug.apk
          path: android/app/build/outputs/apk/debug/*.apk

      # Prepare Keystore
      - name: Prepare Release Keystore
        if: ${{ secrets.ANDROID_KEYSTORE_BASE64 != '' }}
        working-directory: android
        run: echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > "${ANDROID_KEYSTORE_PATH}"

      # Signed Release APK
      - name: Build Release APK
        if: ${{ secrets.ANDROID_KEYSTORE_BASE64 != '' }}
        working-directory: android
        env:
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: ./gradlew assembleRelease --no-daemon
        
      - name: Upload Release APK
        if: ${{ secrets.ANDROID_KEYSTORE_BASE64 != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: AIKEYS-release-signed.apk
          path: android/app/build/outputs/apk/release/*.apk

      # Signed Release AAB
      - name: Build Release AAB
        if: ${{ secrets.ANDROID_KEYSTORE_BASE64 != '' }}
        working-directory: android
        env:
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: ./gradlew bundleRelease --no-daemon
        
      - name: Upload Release AAB
        if: ${{ secrets.ANDROID_KEYSTORE_BASE64 != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: AIKEYS-release.aab
          path: android/app/build/outputs/bundle/release/*.aab

      # Play Store Upload
      - name: Upload to Play Store
        if: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON != '' }}
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
          packageName: ${{ env.PACKAGE_NAME }}
          releaseFiles: android/app/build/outputs/bundle/release/*.aab
          track: ${{ secrets.PLAY_TRACK || 'internal' }}
          status: ${{ secrets.PLAY_RELEASE_STATUS || 'draft' }}
